# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://herdsman.me
date_format: "ordinal"
title: Herdsman
subtitle: "Faith is about believing in someone or something. "
description: "Herdsman Blog"
keywords: Herdsman
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/herds-man/herds-man.github.io
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 李玮
organization: Changhong, Inc.
organization_url: http://cn.changhong.com
location: Sichuan, China
email: drmfly.liw@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /open-source/
    label: 开源

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#    - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
    - jekyll-github-metadata
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: drmfly
#douban_username: drmfly
facebook_username: drmfly1234
#weibo_username: drmfly
#zhihu_username: drmfly
twitter_username: drmfly

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
#duoshuo_username: drmfly
disqus_username: drmfly
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-88249106-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, Golang,kubernetes, Docker,Linux]
skill_mobile_app_keywords: [Java]
#skill_windows_keywords: []

# ---------------- #
# Github metadata  #
# ---------------- #
repository: herds-man/herds-man.github.io
